import type { Metadata } from "next";
import { rootFontClassName } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en-GB" className={rootFontClassName}>
      <body>{children}</body>
    </html>
  );
}
