import type { Metadata } from "next";
import { Geist } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

import SiteHeader from "@/components/layout/SiteHeader/SiteHeader";
import SiteFooter from "@/components/layout/SiteFooter/SiteFooter";
import next from "next";

const monaspaceNeon = localFont({
  src: "./fonts/Monaspace_Neon_Var.woff2",
  variable: "--font-monaspace-neon",
  weight: "200 800",
  display: "swap",
});

const monaspaceArgon = localFont({
  src: "./fonts/Monaspace_Argon_Var.woff2",
  variable: "--font-monaspace-argon",
  weight: "200 800",
  display: "swap",
});

const monaspaceXenon = localFont({
  src: "./fonts/Monaspace_Xenon_Var.woff2",
  variable: "--font-monaspace-xenon",
  weight: "200 800",
  display: "swap",
});

const monaspaceRadon = localFont({
  src: "./fonts/Monaspace_Radon_Var.woff2",
  variable: "--font-monaspace-radon",
  weight: "200 800",
  display: "swap",
});

const monaspaceKrypton = localFont({
  src: "./fonts/Monaspace_Krypton_Var.woff2",
  variable: "--font-monaspace-krypton",
  weight: "200 800",
  display: "swap",
});

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en-GB">
      <body
        className={`${monaspaceArgon.variable} ${monaspaceNeon.variable} ${monaspaceXenon.variable} ${monaspaceRadon.variable} ${monaspaceKrypton.variable} ${geistSans.variable} antialiased`}
      >
        <SiteHeader />
        {children}
        <SiteFooter />
      </body>
    </html>
  );
}
